spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/secureapp
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <CLIENT_ID>
            clientSecret: <CLIENT_SECRET>
            scope:
            - email
            - profile